### ISSUE TITLE
Cannot authenticate using Basic Access Authentication

### ISSUE THREAD

**Issue by Blackrush** [Mangopay/mangopay2-php-sdk#259]
Hello,

I am not able to authenticate using Basic Access Authentication as it gives me this error although I'm using the exact same credentials as the one used to authenticate into the dashboard. Note that the password contains non-alphanumeric characters and is more than 20 characters long.

```
MangoPay\Libraries\ResponseException: Unauthorized in /vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php:290
Stack trace:
#0 /vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php(150): MangoPay\Libraries\RestTool->CheckResponseCode(401, Object(stdClass))
#1 /vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiOAuth.php(28): MangoPay\Libraries\RestTool->Request('/oauth/token ', 'POST', Array)
#2 /vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthorizationTokenManager.php(33): MangoPay\Libraries\ApiOAuth->CreateToken()
#3 /vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthenticationHelper.php(83): MangoPay\Libraries\AuthorizationTokenManager->GetToken('3e6cd91eaa8aff9...')
#4 /vendor/mangopay/php-sdk-v2/MangoPay/Libraries/AuthenticationHelper.php(27): MangoPay\Libraries\AuthenticationHelper->GetHttpHeaderStrong()
#5 /vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php(260): MangoPay\Libraries\AuthenticationHelper->GetHttpHeaderKey()
#6 /vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php(183): MangoPay\Libraries\RestTool->GetHttpHeaders(NULL)
#7 /vendor/mangopay/php-sdk-v2/MangoPay/Libraries/RestTool.php(137): MangoPay\Libraries\RestTool->BuildRequest('/users', Object(MangoPay\Pagination), Array, NULL)
#8 /vendor/mangopay/php-sdk-v2/MangoPay/Libraries/ApiBase.php(297): MangoPay\Libraries\RestTool->Request('/users', 'GET', NULL, NULL, Object(MangoPay\Pagination), Array)
#9 /vendor/mangopay/php-sdk-v2/MangoPay/ApiUsers.php(39): MangoPay\Libraries\ApiBase->GetList('users_all', Object(MangoPay\Pagination), NULL, NULL, NULL, NULL)
#10 /mangopay.php(21): MangoPay\ApiUsers->GetAll()
#11 {main}%
```

Here is the code I used

```php
<?php
require_once "vendor/autoload.php";

$api = new MangoPay\MangoPayApi();

// configuration
$api->Config->ClientId = REDACTED;
$api->Config->ClientPassword = REDACTED;
$api->Config->TemporaryFolder = __DIR__.'/var/mangopay';
//$api->Config->BaseUrl = 'https://api.mangopay.com';//uncomment this to use the production environment

//uncomment any of the following to use a custom value (these are all entirely optional)
//$api->Config->CurlResponseTimeout = 20;//The cURL response timeout in seconds (its 30 by default)
//$api->Config->CurlConnectionTimeout = 60;//The cURL connection timeout in seconds (its 80 by default)
//$api->Config->CertificatesFilePath = ''; //Absolute path to file holding one or more certificates to verify the peer with (if empty, there won't be any verification of the peer's certificate)

// call some API methods...
try {
    echo "fetch all users\n";
    $users = $api->Users->GetAll();
    print_r($users);
} catch(MangoPay\Libraries\ResponseException $e) {
    // handle/log the response exception with code $e->GetCode(), message $e->GetMessage() and error(s) $e->GetErrorDetails()
    echo $e;
} catch(MangoPay\Libraries\Exception $e) {
    // handle/log the exception $e->GetMessage()
    echo $e;
}
```

**Comment by Blackrush** [comment]
Null and void

**Comment by XemaA** [comment]
Hello @volgar1x  ! I have the same problem! please how did you fix this . thanks
