### ISSUE TITLE
Timeout when call to https://homologation-webpayment.payline.com/webpayment/getToken

### ISSUE THREAD

**Issue by duykhanh91** [Mangopay/mangopay2-php-sdk#536]
Hi,
I can't connect to `https://homologation-webpayment.payline.com/webpayment/getToken` when create card from the 12/12/2021. But before the 12/12/2021, it working well.
can you help me check it

```
exception 'ErrorException' with message 'file_get_contents(https://homologation-webpayment.payline.com/webpayment/getToken): failed to open stream: Operation timed out' in /Applications/MAMP/htdocs/ecodropapi/api/app/Http/Controllers/PaymentCardController.php:588
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_get_conten...', '/Applications/M...', 588, Array)
#1 /Applications/MAMP/htdocs/ecodropapi/api/app/Http/Controllers/PaymentCardController.php(588): file_get_contents('https://homolog...', false, Resource id #424)
#2 /Applications/MAMP/htdocs/ecodropapi/api/app/Http/Controllers/PaymentCardController.php(680): App\Http\Controllers\PaymentCardController->registrationCards(Object(MangoPay\CardRegistration), Array)
#3 /Applications/MAMP/htdocs/ecodropapi/api/app/Http/Controllers/PaymentCardController.php(158): App\Http\Controllers\PaymentCardController->createCards(Array, Object(App\User))
#4 [internal function]: App\Http\Controllers\PaymentCardController->store(Object(Illuminate\Http\Request))
#5 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#6 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('store', Array)
#7 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(190): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\PaymentCardController), 'store')
#8 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#9 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /Applications/MAMP/htdocs/ecodropapi/api/app/Http/Middleware/CORS.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\CORS->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#19 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#22 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(644): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(618): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(596): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 /Applications/MAMP/htdocs/ecodropapi/api/app/Http/Middleware/CORS.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\CORS->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 /Applications/MAMP/htdocs/ecodropapi/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#38 /Applications/MAMP/htdocs/ecodropapi/api/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#39 {main}  
```

**Comment by fredericdelordm** [comment]
Hello @duykhanh91, we are looking into it

**Comment by daitxdirox** [comment]
@fredericdelordm is there any news?

**Comment by fredericdelordm** [comment]
Hello @daitxdirox, you are facing the same issue?

**Comment by daica25101** [comment]
Hi @fredericdelordm . We're having the same issue. Can you help us to check ?

**Comment by daica25101** [comment]
We're receiving a time out error while posting the card info to "https://homologation-webpayment.payline.com/webpayment/getToken"

**Comment by fredericdelordm** [comment]
Ok @daica25101, we are looking into it

**Comment by fredericdelordm** [comment]
@duykhanh91 @daica25101 @daitxdirox Are you having the issue in production or in sandbox?

**Comment by daitxdirox** [comment]
We have the issue in sandbox env, we don't have production env.

**Comment by duykhanh91** [comment]
> @duykhanh91 @daica25101 @daitxdirox Are you having the issue in production or in sandbox?

It only for Sandbox

**Comment by daica25101** [comment]
Hi @fredericdelordm . It seems to be that the homologation  API is blocking the ip region from Viet Nam. I tried changing my ip to another country and it worked. So can you provide any solution for this ?

**Comment by fredericdelordm** [comment]
Hello @daica25101, I'll share this info with the support team and get back to you.

**Comment by IdareYouss** [comment]
Hello Fredericdelordm, hope you are good
Do you have any news on this topic please ?
Please let me know
Regards

**Comment by IdareYouss** [comment]
Hello @fredericdelordm  , please if you have some news on this topic ,send me a mail on oussama.ganibardi@idareyou.io 
Regards
